######################################
## Custom Web Almanac GitHub action ##
######################################
#
# This updates the current draft release notes with this commit
# Excluding certain automated commits (e.g. Generate Chapters or Ebooks)
#
name: Add to Release Notes
on:
  push:
    branches:
      - main
jobs:
  release-notes:
    runs-on: ubuntu-20.04
    if: github.repository == 'HTTPArchive/almanac.httparchive.org'
    steps:
    - name: Update release notes
      uses: release-drafter/release-drafter@v5.19.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
