######################################
## Custom Web Almanac GitHub action ##
######################################
#
# This generates the chapters and tests the website when a pull request is
# opened (or added to) on the original repo
#
name: Check Translation Lengths
on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        * * * * *
    - cron: '45 9 * * 0'
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/content/*/*/*.md'
      - 'src/templates/*/*/*.html'
      - 'src/templates/*/*.html'

jobs:
  check_lengths:
    name: Check Lengths
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          path: this_run
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0
      - name: Checkout Code
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v6
        with:
          path: original
          ref: main
          repository: HTTPArchive/almanac.httparchive.org
      - name: Test changed translations
        if: github.event_name == 'pull_request'
        env:
          RUN_TYPE: ${{ github.event_name }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          cd this_run/src
          ./tools/scripts/check_translation_length.sh
      - name: Test all translations
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
        run: |
          cd this_run/src
          ./tools/scripts/check_translation_length.sh -a
