######################################
## Custom Web Almanac GitHub action ##
######################################
#
# Updates timestamps, increments CSS, and then runs "npm run generate"
# on any pushes to main for markdown, templates or generate scripts
#
# Then it tests the website
#
# Then we open a Pull Request for any changes generated.
#
# We do it on a push, rather than on pull request, and only on main to
# avoid needing GitHub Personal Access Tokens and to avoid merge conflicts
#
name: Generate Chapters on Push
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/config/**
      - src/**.py
      - src/requirements.txt
      - src/content/**
      - src/templates/**
      - src/tools/**
      - src/static/css/**
      - src/static/js/**
      - src/package.json
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'HTTPArchive/almanac.httparchive.org'
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Update CSS version for modified CSS files
      if: github.event_name == 'push'
      env:
        COMMIT_SHA: ${{ github.event.commits[0].id }}
      run: |
        echo "files changed in commit $COMMIT_SHA:"
        git diff-tree --no-commit-id --name-only -r $COMMIT_SHA
        echo "Incrementing any references to changed CSS files"
        git diff-tree --diff-filter=AM --no-commit-id --name-only -r $COMMIT_SHA src/static/css | grep "\.css" | sed 's!.*/!!' | sed "s/\(.*\)/s\/\1?v=[0-9][0-9]*\/\1?v=$(date +%Y%m%d%H%M%S)\//" | sed -f - -i src/templates/base/*/*.html
        git diff-tree --diff-filter=AM --no-commit-id --name-only -r $COMMIT_SHA src/static/css | grep "\.css" | sed 's!.*/!!' | sed "s/\(.*\)/s\/\1?v=[0-9][0-9]*\/\1?v=$(date +%Y%m%d%H%M%S)\//" | sed -f - -i src/templates/base.html
        git diff
    - name: Update JS version for modified CSS files
      if: github.event_name == 'push'
      env:
        COMMIT_SHA: ${{ github.event.commits[0].id }}
      run: |
        echo "files changed in commit $COMMIT_SHA:"
        git diff-tree --no-commit-id --name-only -r $COMMIT_SHA
        echo "Incrementing any references to changed JS files"
        git diff-tree --diff-filter=AM --no-commit-id --name-only -r $COMMIT_SHA src/static/js | grep "\.js" | sed 's!.*/!!' | sed "s/\(.*\)/s\/\1?v=[0-9][0-9]*\/\1?v=$(date +%Y%m%d%H%M%S)\//" | sed -f - -i src/templates/base/*/*.html
        git diff-tree --diff-filter=AM --no-commit-id --name-only -r $COMMIT_SHA src/static/js | grep "\.js" | sed 's!.*/!!' | sed "s/\(.*\)/s\/\1?v=[0-9][0-9]*\/\1?v=$(date +%Y%m%d%H%M%S)\//" | sed -f - -i src/templates/base.html
        git diff
    - name: Update timestamp for modified files
      if: github.event_name == 'push'
      env:
        COMMIT_SHA: ${{ github.event.commits[0].id }}
      run: |
        echo "files changed in commit $COMMIT_SHA:"
        git diff-tree --no-commit-id --name-only -r $COMMIT_SHA
        echo "Updating timestamp in any markdown chapter files"
        git diff-tree --diff-filter=AM --no-commit-id --name-only -r $COMMIT_SHA src/content | grep "^src\/content\/[a-z]*\/[0-9]*\/[a-z0-9-]*.md" | xargs -r sed -i "s/^last_updated: [0-9-]*T/last_updated: $(date '+%Y-%m-%d')T/"
        echo "Updating timestamp in any template files"
        git diff-tree --diff-filter=AM --no-commit-id --name-only -r $COMMIT_SHA src/templates | grep "^src\/templates\/[a-z][a-z]\/20[0-9][0-9]\/[a-zA-Z0-9_]*.html" | xargs -r sed -i "s/{% block date_modified %}[0-9-]*T/{% block date_modified %}$(date '+%Y-%m-%d')T/"
        git diff-tree --diff-filter=AM --no-commit-id --name-only -r $COMMIT_SHA src/templates | grep "^src\/templates\/[a-z][a-z]\/[a-zA-Z0-9_]*.html" | xargs -r sed -i "s/{% block date_modified %}[0-9-]*T/{% block date_modified %}$(date '+%Y-%m-%d')T/"
        echo "Updated timestamps:"
        git diff
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version:  12.x
    - name: Generate the chapters
      run: |
        echo "regenerating chapters"
        cd src
        npm install
        echo "regenerating chapters"
        npm run generate
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        cd src
        pip install -r requirements.txt
    - name: Run pytest
      run: |
        cd src
        pytest
    - name: Run website
      run: |
        cd src
        python main.py background &
    - name: Run tests
      run: |
        cd src
        npm run tests
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        title: Update datestamps and generate chapters
        branch-suffix: timestamp
        commit-message: Generate Chapters
        body: |
          Updated datestamps and regenerated the chapters
          - Please merge today or we'll get new datestamps tomorrow and you'll have to merge again!
          - Auto-generated by [create-pull-request][1] GitHub Action

          [1]: https://github.com/peter-evans/create-pull-request
        labels: generate chapters
    - name: Check outputs
      run: echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
