###########################
## Lint All SQL code
###########################
#
name: Lint SQL
on:
  workflow_dispatch:
  pull_request:
    paths:
      src/requirements.txt
jobs:
  lint:
    name: Lint SQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Lint SQL code
        if: |
            github.event_name == 'workflow_dispatch' ||
            startsWith(github.event.pull_request.title,'Bump sqlfluff') == true
        run: |
          pip install -r src/requirements.txt
          sqlfluff lint sql -p 4
